# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-07 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=20)),
                ('species', models.PositiveSmallIntegerField(choices=[(0, b'dog'), (1, b'cat')])),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VaccinationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vaccinated', models.DateField()),
                ('date_due', models.DateField()),
                ('pets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccination_reminder.Pets')),
            ],
        ),
        migrations.CreateModel(
            name='Vaccinations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccination_name', models.CharField(max_length=50)),
                ('species', models.PositiveSmallIntegerField(choices=[(0, b'dog_only'), (1, b'cat_only'), (2, b'both_species')])),
                ('first_shot_age_months', models.PositiveSmallIntegerField(default=0)),
                ('second_shot_age_months', models.PositiveSmallIntegerField(null=True)),
                ('third_shot_age_months', models.PositiveSmallIntegerField(null=True)),
                ('fourth_shot_age_months', models.PositiveSmallIntegerField(null=True)),
                ('vaccination_frequency_years', models.PositiveSmallIntegerField(default=0)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='vaccinationhistory',
            name='vaccinations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccination_reminder.Vaccinations'),
        ),
    ]
