# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-10 17:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination_reminder', '0017_auto_20170708_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='birthdate',
            field=models.DateField(default=datetime.datetime(2017, 7, 10, 13, 51, 18, 983000)),
        ),
    ]
