# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-10 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination_reminder', '0018_pets_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='birthdate',
            field=models.DateField(),
        ),
    ]
