# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-11 16:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination_reminder', '0019_auto_20170710_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='pets',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vaccinationhistory',
            name='pets',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='vaccination_reminder.Pets'),
        ),
        migrations.AlterField(
            model_name='vaccinationhistory',
            name='vaccinations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='vaccination_reminder.Vaccinations'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
