# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-12 23:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination_reminder', '0020_auto_20170711_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationhistory',
            name='pets',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='vaccination_reminder.Pets'),
        ),
    ]
