# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-13 00:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination_reminder', '0021_auto_20170712_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationhistory',
            name='pets',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccination_reminder.Pets'),
        ),
    ]
